# Generated by Django 3.1.4 on 2020-12-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_remove_art_user'),
        ('artbox_auth', '0004_auto_20201211_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
