# Generated by Django 3.1.4 on 2020-12-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_art_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
