# Generated by Django 3.1.4 on 2020-12-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20201211_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='user',
        ),
    ]
