# Generated by Django 3.1.4 on 2020-12-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_art_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='user',
        ),
    ]
