# Generated by Django 3.1.4 on 2020-12-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_remove_art_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='type',
            field=models.CharField(choices=[('abstract', 'Abstract'), ('cartoon', 'Cartoon'), ('graffiti', 'Graffiti'), ('other', 'Other')], default='other', max_length=8),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.art')),
            ],
        ),
    ]
