# Generated by Django 3.1.4 on 2020-12-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0012_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
