# Generated by Django 3.1.4 on 2020-12-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_editprofile'),
        ('art', '0013_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('artist', models.CharField(blank=True, max_length=120)),
                ('type', models.CharField(choices=[('abstract', 'Abstract'), ('cartoon', 'Cartoon'), ('graffiti', 'Graffiti'), ('other', 'Other')], default='other', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
